package br.com.sistemapasta.painel.view;
import br.com.sistemapasta.painel.controller.Arquivos;
import br.com.sistemapasta.painel.model.Usuarios;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Álvaro
 */
public class GuiMenu extends javax.swing.JFrame {
    ArrayList <Usuarios> usuarios_arraylist;
    Usuarios usuarios;
    Arquivos arquivo;
    private void RegistrolimparCampos(){
    RegistrojTextFieldUsuario.setText("");
    RegistrojPasswordFieldSenha.setText("");
    RegistrojRadioButtonMasculino.setSelected(false);
    RegistrojRadioButtonFeminino.setSelected(false);
    RegistrojSpinnerIdade.setValue(0);
    }
    
    /**
     * Creates new form GuiMenu
     */
    public GuiMenu(){
        usuarios_arraylist = new ArrayList <Usuarios>();
        usuarios = new Usuarios();
        arquivo = new Arquivos();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jInternalFrameRegistro = new javax.swing.JInternalFrame();
        RegistrojLabelUsuário = new javax.swing.JLabel();
        RegistrojLabelSenha = new javax.swing.JLabel();
        RegistrojTextFieldUsuario = new javax.swing.JTextField();
        RegistrojLabelSexo = new javax.swing.JLabel();
        RegistrojRadioButtonMasculino = new javax.swing.JRadioButton();
        RegistrojRadioButtonFeminino = new javax.swing.JRadioButton();
        RegistrojLabelIdade = new javax.swing.JLabel();
        RegistrojSpinnerIdade = new javax.swing.JSpinner();
        RegistrojButtonRegistrar = new javax.swing.JButton();
        RegistrojPasswordFieldSenha = new javax.swing.JPasswordField();
        jInternalFrameLogin = new javax.swing.JInternalFrame();
        LoginjLabelBemVindo = new javax.swing.JLabel();
        LoginjTextFieldUsuario = new javax.swing.JTextField();
        LoginjTextFieldSenha = new javax.swing.JTextField();
        LoginjButtonLogar = new javax.swing.JButton();
        jInternalFramePesquisar = new javax.swing.JInternalFrame();
        PesquisarjTextFieldUsuario = new javax.swing.JTextField();
        PesquisarjButtonPesquisar = new javax.swing.JButton();
        PesquisarjLabelIdade = new javax.swing.JLabel();
        PesquisarjLabelSexo = new javax.swing.JLabel();
        PesquisarjLabelUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemLogin = new javax.swing.JMenuItem();
        jMenuItemRegistrar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemPesquisar = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Sitka Subheading", 0, 48)); // NOI18N
        jLabel1.setText("Olá!");
        jPanel.add(jLabel1);
        jLabel1.setBounds(590, 10, 87, 61);

        jInternalFrameRegistro.setTitle("Registro");
        jInternalFrameRegistro.setToolTipText("");
        jInternalFrameRegistro.setMaximumSize(new java.awt.Dimension(507, 403));
        jInternalFrameRegistro.setMinimumSize(new java.awt.Dimension(507, 403));
        jInternalFrameRegistro.setVisible(false);

        RegistrojLabelUsuário.setText("Usuário:");

        RegistrojLabelSenha.setText("Senha:");

        RegistrojLabelSexo.setText("Sexo:");

        RegistrojRadioButtonMasculino.setText("Masculino");
        RegistrojRadioButtonMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrojRadioButtonMasculinoActionPerformed(evt);
            }
        });

        RegistrojRadioButtonFeminino.setText("Feminino");
        RegistrojRadioButtonFeminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrojRadioButtonFemininoActionPerformed(evt);
            }
        });

        RegistrojLabelIdade.setText("Idade:");

        RegistrojButtonRegistrar.setText("Registrar");
        RegistrojButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrojButtonRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrameRegistroLayout = new javax.swing.GroupLayout(jInternalFrameRegistro.getContentPane());
        jInternalFrameRegistro.getContentPane().setLayout(jInternalFrameRegistroLayout);
        jInternalFrameRegistroLayout.setHorizontalGroup(
            jInternalFrameRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameRegistroLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jInternalFrameRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RegistrojLabelUsuário)
                    .addComponent(RegistrojLabelSenha)
                    .addComponent(RegistrojLabelSexo)
                    .addComponent(RegistrojLabelIdade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrameRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrameRegistroLayout.createSequentialGroup()
                        .addGroup(jInternalFrameRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jInternalFrameRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(RegistrojTextFieldUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                .addComponent(RegistrojPasswordFieldSenha))
                            .addGroup(jInternalFrameRegistroLayout.createSequentialGroup()
                                .addComponent(RegistrojRadioButtonMasculino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                                .addComponent(RegistrojRadioButtonFeminino)))
                        .addGap(165, 165, 165))
                    .addGroup(jInternalFrameRegistroLayout.createSequentialGroup()
                        .addComponent(RegistrojSpinnerIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameRegistroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RegistrojButtonRegistrar)
                .addGap(39, 39, 39))
        );
        jInternalFrameRegistroLayout.setVerticalGroup(
            jInternalFrameRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameRegistroLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jInternalFrameRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistrojLabelUsuário)
                    .addComponent(RegistrojTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jInternalFrameRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistrojLabelSenha)
                    .addComponent(RegistrojPasswordFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jInternalFrameRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistrojLabelSexo)
                    .addComponent(RegistrojRadioButtonFeminino)
                    .addComponent(RegistrojRadioButtonMasculino))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistrojLabelIdade)
                    .addComponent(RegistrojSpinnerIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(RegistrojButtonRegistrar)
                .addGap(24, 24, 24))
        );

        jPanel.add(jInternalFrameRegistro);
        jInternalFrameRegistro.setBounds(400, 100, 460, 400);

        jInternalFrameLogin.setTitle("Login");
        jInternalFrameLogin.setMaximumSize(new java.awt.Dimension(507, 403));
        jInternalFrameLogin.setMinimumSize(new java.awt.Dimension(507, 403));
        jInternalFrameLogin.setPreferredSize(new java.awt.Dimension(507, 403));
        jInternalFrameLogin.setVisible(false);
        jInternalFrameLogin.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginjLabelBemVindo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LoginjLabelBemVindo.setText("Bem vindo!");
        jInternalFrameLogin.getContentPane().add(LoginjLabelBemVindo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 120, -1));
        jInternalFrameLogin.getContentPane().add(LoginjTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 120, -1));
        jInternalFrameLogin.getContentPane().add(LoginjTextFieldSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 120, -1));

        LoginjButtonLogar.setText("Logar");
        jInternalFrameLogin.getContentPane().add(LoginjButtonLogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 250, 80, -1));

        jPanel.add(jInternalFrameLogin);
        jInternalFrameLogin.setBounds(400, 100, 460, 400);

        jInternalFramePesquisar.setTitle("Pesquisar");
        jInternalFramePesquisar.setVisible(false);

        PesquisarjButtonPesquisar.setText("Pesquisar");
        PesquisarjButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarjButtonPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFramePesquisarLayout = new javax.swing.GroupLayout(jInternalFramePesquisar.getContentPane());
        jInternalFramePesquisar.getContentPane().setLayout(jInternalFramePesquisarLayout);
        jInternalFramePesquisarLayout.setHorizontalGroup(
            jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFramePesquisarLayout.createSequentialGroup()
                .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFramePesquisarLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(PesquisarjTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFramePesquisarLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(PesquisarjButtonPesquisar)))
                .addContainerGap(153, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFramePesquisarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PesquisarjLabelUsuario)
                    .addComponent(PesquisarjLabelSexo)
                    .addComponent(PesquisarjLabelIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(198, 198, 198))
        );
        jInternalFramePesquisarLayout.setVerticalGroup(
            jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFramePesquisarLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(PesquisarjTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PesquisarjButtonPesquisar)
                .addGap(25, 25, 25)
                .addComponent(PesquisarjLabelUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PesquisarjLabelIdade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PesquisarjLabelSexo)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        jPanel.add(jInternalFramePesquisar);
        jInternalFramePesquisar.setBounds(400, 100, 460, 400);

        getContentPane().add(jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        jMenu1.setText("Área do Usuário");

        jMenuItemLogin.setText("Login");
        jMenuItemLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLoginActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemLogin);

        jMenuItemRegistrar.setText("Registrar");
        jMenuItemRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemRegistrar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Área do Administrador");

        jMenuItemPesquisar.setText("Pesquisar");
        jMenuItemPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPesquisarActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemPesquisar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrojRadioButtonMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrojRadioButtonMasculinoActionPerformed
        RegistrojRadioButtonFeminino.setSelected(false);
    }//GEN-LAST:event_RegistrojRadioButtonMasculinoActionPerformed

    private void RegistrojRadioButtonFemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrojRadioButtonFemininoActionPerformed
        RegistrojRadioButtonMasculino.setSelected(false);
    }//GEN-LAST:event_RegistrojRadioButtonFemininoActionPerformed

    private void jMenuItemLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLoginActionPerformed
        jInternalFramePesquisar.setVisible(false);
        jInternalFrameRegistro.setVisible(false);
        jInternalFrameLogin.setVisible(true);
    }//GEN-LAST:event_jMenuItemLoginActionPerformed

    private void jMenuItemRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarActionPerformed
        RegistrolimparCampos();
        jInternalFramePesquisar.setVisible(false);
        jInternalFrameLogin.setVisible(false);
        jInternalFrameRegistro.setVisible(true);
    }//GEN-LAST:event_jMenuItemRegistrarActionPerformed

    private void RegistrojButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrojButtonRegistrarActionPerformed
        usuarios.setUsuario(RegistrojTextFieldUsuario.getText());
        usuarios.setSenha(RegistrojPasswordFieldSenha.getText()); 
        if (RegistrojRadioButtonMasculino.isSelected()){
        usuarios.setSexo("Masculino");
        }
        if (RegistrojRadioButtonFeminino.isSelected()){
        usuarios.setSexo("Feminino");
        }
        usuarios.setIdade((int)RegistrojSpinnerIdade.getValue());
        
        jInternalFrameRegistro.setVisible(false);
       
        System.out.println ("\n Usuário: " + usuarios.getUsuario() + "\n Senha: " + usuarios.getSenha() + "\n Sexo: " + usuarios.getSexo().toString() + "\n Idade: " + usuarios.getIdade());
        
        usuarios_arraylist.add(usuarios);
        
        try {
            arquivo.salvar(usuarios);
            System.out.println ("Os dados foram salvos");
            usuarios = new Usuarios();
        } 
        catch (IOException ex) {
            System.out.println("O usuário não foi salvo no arquivo");
        }
        RegistrolimparCampos();  
    }//GEN-LAST:event_RegistrojButtonRegistrarActionPerformed

    private void PesquisarjButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarjButtonPesquisarActionPerformed

        for (int cont = 0; usuarios_arraylist.size() > cont ; cont++){
             
           if (PesquisarjTextFieldUsuario.getText().equals(usuarios_arraylist.get(cont).getUsuario())){
            PesquisarjLabelUsuario.setText(usuarios_arraylist.get(cont).getUsuario());
            PesquisarjLabelIdade.setText(String.valueOf(usuarios_arraylist.get(cont).getIdade()));
            PesquisarjLabelSexo.setText(usuarios_arraylist.get(cont).getSexo());
           }
        
        }
       
    }//GEN-LAST:event_PesquisarjButtonPesquisarActionPerformed

    private void jMenuItemPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPesquisarActionPerformed
        PesquisarjTextFieldUsuario.setText("");
        jInternalFrameLogin.setVisible(false);
        jInternalFrameRegistro.setVisible(false);
        jInternalFramePesquisar.setVisible(true);
    }//GEN-LAST:event_jMenuItemPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginjButtonLogar;
    private javax.swing.JLabel LoginjLabelBemVindo;
    private javax.swing.JTextField LoginjTextFieldSenha;
    private javax.swing.JTextField LoginjTextFieldUsuario;
    private javax.swing.JButton PesquisarjButtonPesquisar;
    private javax.swing.JLabel PesquisarjLabelIdade;
    private javax.swing.JLabel PesquisarjLabelSexo;
    private javax.swing.JLabel PesquisarjLabelUsuario;
    private javax.swing.JTextField PesquisarjTextFieldUsuario;
    private javax.swing.JButton RegistrojButtonRegistrar;
    private javax.swing.JLabel RegistrojLabelIdade;
    private javax.swing.JLabel RegistrojLabelSenha;
    private javax.swing.JLabel RegistrojLabelSexo;
    private javax.swing.JLabel RegistrojLabelUsuário;
    private javax.swing.JPasswordField RegistrojPasswordFieldSenha;
    private javax.swing.JRadioButton RegistrojRadioButtonFeminino;
    private javax.swing.JRadioButton RegistrojRadioButtonMasculino;
    private javax.swing.JSpinner RegistrojSpinnerIdade;
    private javax.swing.JTextField RegistrojTextFieldUsuario;
    private javax.swing.JInternalFrame jInternalFrameLogin;
    private javax.swing.JInternalFrame jInternalFramePesquisar;
    private javax.swing.JInternalFrame jInternalFrameRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemLogin;
    private javax.swing.JMenuItem jMenuItemPesquisar;
    private javax.swing.JMenuItem jMenuItemRegistrar;
    private javax.swing.JPanel jPanel;
    // End of variables declaration//GEN-END:variables
}
